aws_profile = "yummy"
aws_region = "eu-central-1"
app_id = "yummy"
app_name = "Yummy App"
bucket_name = "yummy.timafe.net"
identity_pool_name = "yummy"
user_pool_name = "yummy"
role_name_prefix = "yummy"
table_name_prefix = "yummy"
env = "dev"

route53_subdomain = "yummy-dev"
route53_zone = "timafe.net."
route53_alias_zone_id = "Z21DNDUVLTQW6Q"